INSERT INTO `Categories`(`id`, `name`) VALUES ('2bdFPJUvFo', '18XX');
INSERT INTO `Categories`(`id`, `name`) VALUES ('85OKv8p5Ow', '4x');
INSERT INTO `Categories`(`id`, `name`) VALUES ('FMKgeuNEII', '80s');
INSERT INTO `Categories`(`id`, `name`) VALUES ('hBqZ3Ar4RJ', 'Abstract');
INSERT INTO `Categories`(`id`, `name`) VALUES ('GtuMb7ei27', 'Accessory');
INSERT INTO `Categories`(`id`, `name`) VALUES ('OE07lsfVqf', 'Adult');
INSERT INTO `Categories`(`id`, `name`) VALUES ('KUBCKBkGxV', 'Adventure');
INSERT INTO `Categories`(`id`, `name`) VALUES ('DjAhqEHOD0', 'Aerial Warfare');
INSERT INTO `Categories`(`id`, `name`) VALUES ('20iDvpbh7A', 'Age of Reason');
INSERT INTO `Categories`(`id`, `name`) VALUES ('tJxatX2ZbW', 'Aliens');
INSERT INTO `Categories`(`id`, `name`) VALUES ('nWDac9tQzt', 'Alternate History');
INSERT INTO `Categories`(`id`, `name`) VALUES ('dghLhwyxVb', 'American History');
INSERT INTO `Categories`(`id`, `name`) VALUES ('4mOtRRwSoj', 'American West');
INSERT INTO `Categories`(`id`, `name`) VALUES ('a8NM5cugJX', 'Ancient');
INSERT INTO `Categories`(`id`, `name`) VALUES ('MWoxgHrOJD', 'Animals');
INSERT INTO `Categories`(`id`, `name`) VALUES ('eFaACC6y2c', 'Apocalyptic');
INSERT INTO `Categories`(`id`, `name`) VALUES ('CBboNLI1Uj', 'Arabian');
INSERT INTO `Categories`(`id`, `name`) VALUES ('k0dglq5j6N', 'Art');
INSERT INTO `Categories`(`id`, `name`) VALUES ('Bq6M0TJyg7', 'Asymmetric');
INSERT INTO `Categories`(`id`, `name`) VALUES ('QB4sEpx1Uu', 'Aviation');
INSERT INTO `Categories`(`id`, `name`) VALUES ('wpItJuRDiz', 'Banking');
INSERT INTO `Categories`(`id`, `name`) VALUES ('pwt9HAzEa6', 'Battle Royale');
INSERT INTO `Categories`(`id`, `name`) VALUES ('PinhJrhnxU', 'Bluffing');
INSERT INTO `Categories`(`id`, `name`) VALUES ('wLpYxHBexW', 'Book');
INSERT INTO `Categories`(`id`, `name`) VALUES ('fW5vusE96B', 'Campaign');
INSERT INTO `Categories`(`id`, `name`) VALUES ('eX8uuNlQkQ', 'Card Game');
INSERT INTO `Categories`(`id`, `name`) VALUES ('HKaYVNIxAJ', 'Children''s Game');
INSERT INTO `Categories`(`id`, `name`) VALUES ('36WFElclV3', 'Christian');
INSERT INTO `Categories`(`id`, `name`) VALUES ('3Y1dIDLCRw', 'Christmas');
INSERT INTO `Categories`(`id`, `name`) VALUES ('ODWOjWAJj3', 'City Building');
INSERT INTO `Categories`(`id`, `name`) VALUES ('w8XD66FUZ2', 'Civil War');
INSERT INTO `Categories`(`id`, `name`) VALUES ('329DxyFL9D', 'Civilization');
INSERT INTO `Categories`(`id`, `name`) VALUES ('bVMxJo31bS', 'Cold war');
INSERT INTO `Categories`(`id`, `name`) VALUES ('vXxLT0FDTZ', 'Collectible Components');
INSERT INTO `Categories`(`id`, `name`) VALUES ('bSzUpE5oOZ', 'Colonial');
INSERT INTO `Categories`(`id`, `name`) VALUES ('gscaL52VDG', 'Combat');
INSERT INTO `Categories`(`id`, `name`) VALUES ('G5kfqnPBP6', 'Comic Book / Strip');
INSERT INTO `Categories`(`id`, `name`) VALUES ('pacCjl7His', 'Competitive');
INSERT INTO `Categories`(`id`, `name`) VALUES ('ge8pIhEUGE', 'Cooperative');
INSERT INTO `Categories`(`id`, `name`) VALUES ('7DfHn28Pcf', 'Crime');
INSERT INTO `Categories`(`id`, `name`) VALUES ('nfQONtMbDU', 'Cube Rail');
INSERT INTO `Categories`(`id`, `name`) VALUES ('Ef4oYLHNhI', 'Cyberpunk');
INSERT INTO `Categories`(`id`, `name`) VALUES ('bCBXJy9qDw', 'Deduction');
INSERT INTO `Categories`(`id`, `name`) VALUES ('fh4V5SOLFj', 'Deluxe Edition');
INSERT INTO `Categories`(`id`, `name`) VALUES ('bKrxqD9mYc', 'Dexterity');
INSERT INTO `Categories`(`id`, `name`) VALUES ('mavSOM8vjH', 'Dice');
INSERT INTO `Categories`(`id`, `name`) VALUES ('o7Macrb9q7', 'Dice Tower Combat');
INSERT INTO `Categories`(`id`, `name`) VALUES ('42pmul4oHH', 'Dinosaurs');
INSERT INTO `Categories`(`id`, `name`) VALUES ('zoOGfQ9rK3', 'Dogs');
INSERT INTO `Categories`(`id`, `name`) VALUES ('JMM0TG2MSe', 'Drawing');
INSERT INTO `Categories`(`id`, `name`) VALUES ('We3MM46qBr', 'Drinking');
INSERT INTO `Categories`(`id`, `name`) VALUES ('g2Hwv8t0Y5', 'Dungeon Crawl');
INSERT INTO `Categories`(`id`, `name`) VALUES ('N0TkEGfEsF', 'Economic');
INSERT INTO `Categories`(`id`, `name`) VALUES ('B3NRLMK4xD', 'Educational');
INSERT INTO `Categories`(`id`, `name`) VALUES ('crxgUzJSEz', 'Electronic');