name: Continuous integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-FrontEnd-Tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn
      - run: npx jest
  run-BackEnd-Tests:
    needs: run-FrontEnd-Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn
      - run: npx jest
  deploy:
    needs: [run-FrontEnd-Tests, run-BackEnd-Tests]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: http://137.74.196.230:7320/deploy
          webhook_secret: 9MCYb@WJwL2G-Dz
